services:
    app:
        container_name: player-service-app
        build:
            context: player-service-app/
            dockerfile: Dockerfile
        environment:
        - FLASK_ENV=development
        - FLASK_APP=/app.py
        - DATABASE=/player.db
        ports:
        - 8001:8001
    
    model:
        build:
            context: player-service-model/
            dockerfile: Dockerfile
        ports:
        - 5001:5001
